version: '3.9'

services:
  surrealdb:
    env_file:
      - .surreal_env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:/mydata/mydatabase.db
    image: surrealdb/surrealdb:latest
    volumes:
      - ./DB_DATA:/mydata
    ports:
      - 8000:8000

  backend:
    build:
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/src:/usr/src/myapp/src
      - ./backend/Cargo.lock:/usr/src/myapp/Cargo.lock
      - ./backend/Cargo.toml:/usr/src/myapp/Cargo.toml
      - ./.env:/usr/src/myapp/.env
      # making target a volume helps not having to recompile when rebuilding (disabled because of no space on school macs)
      # - ./subtitle_parser/target:/usr/src/myapp/target
      # no idea how migrations work yet :))))
      # - ./subtitle_parser/migrations:/usr/src/myapp/migrations
    # networks:
      # - database
    ports:
      - 3000:3000
    container_name: backend